#!/usr/bin/env bash
# mise description="Create GitHub Release."
set -e # Exit on error

TOKEN=$1 # Expect first argument is TOKEN with 'contents:write' permissions
VERSION=$(poetry version --short)
OWNER="JKCT"
REPO="awsync"

echo "Creating new GitHub release: '${VERSION}'..."
# Requires token with permissions: contents:write
# https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release
curl -L \
  --silent \
  --output /dev/null \
  --show-error \
  --fail \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/${OWNER}/${REPO}/releases \
# Automatically generate release notes and set as latest version.
  -d '{"tag_name":"'${VERSION}'","name":"'${VERSION}'","generate_release_notes":true,"make_latest":true}'
