---
name: 🐛 Bug
description: Submit a bug report
title: "[BUG]: (short description)"
labels: [bug, new]
body:
  - type: input
    id: awsync-version
    attributes:
      label: awsync version
      description: "The version of awsync being used."
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: "The version of python being used."
      placeholder: 3.12.2
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - OSX
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A descriptive explaination of the bug."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: "Any relevant error log output ie. traceback."
      render: shell
    validations:
      required: false

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: checkboxes
    id: options
    attributes:
      label: Options
      options:
        - label: "I can contribute a fix for this bug."
          required: false
